### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by BoonHean** [themondays/Dwarf#18] opened 2016-06-13 04:46 UTC
The description and comments of an issue doesn't seems to word wrap properly. Several words got divided between 2 lines for my setup.

Other than that, the theme looks great!

**Comment by themondays** [comment] 2016-06-13 06:30
Hi,
Can you drop me a screenshot, I will check  this issue. I've forced word wrap to prevent text overflow inside container.

**Comment by garrettr** [comment] 2016-06-13 19:43
I'm pretty sure this is a duplicate of #11.

**Comment by garrettr** [comment] 2016-06-13 19:45
Here's an example screenshot where you can see how words get broken across lines in display a Project's description. This also applies to issue's descriptions and comments (since they all have `div.wiki`).

![screen shot 2016-06-13 at 12 42 00 pm](https://cloud.githubusercontent.com/assets/407302/16020820/9494f3e2-3164-11e6-9a2f-8ba84eb8d1e4.png)

**Comment by garrettr** [comment] 2016-06-13 19:46
Disabling the following CSS rule fixes the issue for me:

```
.wiki {
    word-break: break-all;
}
```

According to Chrome's DevTools, it's defined in `/themes/dwarf/stylesheets/application.css`.

**Comment by BoonHean** [comment] 2016-06-13 21:20
That works for me. Thanks garrettr!

**Comment by themondays** [comment] 2016-10-02 10:46
Yeah, should be ok, however if you're working on lot of client's issue or bugfixes, sometime you may need to break an incredibly long inputs or links.
Just keep it in mind.

**Closed as completed** 2016-10-02 10:54 UTC
